CC = c++
CFLAGS = -Wall -Wextra -Werror -std=c++98
NAME = zombie
SRC =   ./main.cpp\
		./newZombie.cpp\
		./randomChump.cpp\
		./Zombie.cpp

OBJ = $(SRC:.cpp=.o)

all : $(NAME)

$(NAME) : $(OBJ)
	$(CC) $(CFLAGS) $(OBJ) -o $(NAME)

clean:
	rm -rf $(OBJ)

fclean: clean
	rm -rf $(NAME)

re: fclean all